// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXe7jRKCJy-7JzO_hTI9RfKr07gt1fFPY',
    appId: '1:804427822083:web:88bc3b38a3412ba4078a36',
    messagingSenderId: '804427822083',
    projectId: 'inventory-app-jaypatel',
    authDomain: 'inventory-app-jaypatel.firebaseapp.com',
    storageBucket: 'inventory-app-jaypatel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI6ZktfjG2pQK0NDGrmd5KU5tYuuyLbAE',
    appId: '1:804427822083:android:92d7a2191f995b1c078a36',
    messagingSenderId: '804427822083',
    projectId: 'inventory-app-jaypatel',
    storageBucket: 'inventory-app-jaypatel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGEIITeOXmPUId446hO624JK8df6xuDj0',
    appId: '1:804427822083:ios:41996e10a0625558078a36',
    messagingSenderId: '804427822083',
    projectId: 'inventory-app-jaypatel',
    storageBucket: 'inventory-app-jaypatel.firebasestorage.app',
    iosBundleId: 'com.example.act15',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGEIITeOXmPUId446hO624JK8df6xuDj0',
    appId: '1:804427822083:ios:41996e10a0625558078a36',
    messagingSenderId: '804427822083',
    projectId: 'inventory-app-jaypatel',
    storageBucket: 'inventory-app-jaypatel.firebasestorage.app',
    iosBundleId: 'com.example.act15',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXe7jRKCJy-7JzO_hTI9RfKr07gt1fFPY',
    appId: '1:804427822083:web:0156d7aa6f80974d078a36',
    messagingSenderId: '804427822083',
    projectId: 'inventory-app-jaypatel',
    authDomain: 'inventory-app-jaypatel.firebaseapp.com',
    storageBucket: 'inventory-app-jaypatel.firebasestorage.app',
  );
}
